name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
change-title-escapes: '\<*_&'
template: |
  ```
  
                           ##########
                        ###          ###
                      ##                ##
                    ##                    ##
                   ##   ###          ###   ##
         ####     ##   # o #  #  #  # o #   ##     ####
  ------#    #--------------- #  # ---------------#    #------
  |      ####                 #  #                 ####      |
  |                            ##                            |
  |                                                          |
  |                                                          |
  |                                                          |
  |                        WHAT'S NEW                        |
  |                                                          |
  |                                                          |
  |                                                          |
  |                                                          |
  ------------------------------------------------------------
  
  ```

  $CHANGES